version: "3"
services:
  fivem:
    image: petchstudio/fivem
    container_name: fivem
    stdin_open: true
    tty: true
    volumes:
      - "./FiveM/server.cfg:/srv/server.cfg"
      - "./FiveM/cfx-server-data/resources:/srv/resources"
      - "./FiveM/cfx-server-data/cache:/srv/cache"
    ports:
      - "30120:30120/tcp"
      - "30120:30120/udp"
      - "40120:40120"
    networks:
      - fivem-postgres
  postgres:
    image: "postgres" # use latest official postgres version
    container_name: postgres
    env_file:
      - ./Postgres/database.env # configure postgres
    volumes:
      - ./Postgres/postgres-data:/var/lib/postgresql/data
      - ./Postgres/sql-scripts:/docker-entrypoint-initdb.d/
    expose:
      - "5432"
    ports:
      - 5432:5432
    networks:
      - fivem-postgres
networks:
  fivem-postgres:
    driver: bridge
