
version: '3'
services:
  fivem:
    build: ./FiveM
    container_name: FiveM
    stdin_open: true
    tty: true
    volumes:
      - ./FiveM/configs/server.cfg:/FiveM/configs/server.cfg
      - ./FiveM/resources:/FiveM/resources
      - ./FiveM/cache:/FiveM/cache
  
    ports:
      - "30120:30120/tcp"
      - "30120:30120/udp"
    networks: 
      - fivem-postgres
  postgres:
    image: "postgres" # use latest official postgres version
    container_name: postgres
    env_file:
      - ./Postgres/database.env # configure postgres
    volumes: 
      - ./Postgres/postgres-data:/var/lib/postgresql/data
      - ./Postgres/sql-scripts:/docker-entrypoint-initdb.d/
    expose:
      - "5432"
    ports:
      - 5432:5432
    networks:
      - fivem-postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - ./Postgres/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - "postgres"
    networks:
      - fivem-postgres
networks:
  fivem-postgres:
    driver: bridge