version: "3"
services:
  fivem:
    build: ./FiveM
    container_name: FiveM
    stdin_open: true
    tty: true
    volumes:
      - ./FiveM/server-data:/FiveM/server-data
    environment:
      GAME_CONFIG: ./FiveM/configs/server.cfg
      SERVER_KEY: placeyourkeyhere
      SRV_ADR: https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/
      UID: 99
      GID: 100
    ports:
      - "30120:30120/tcp"
      - "30120:30120/udp"
      - "40120:40120"
    networks:
      - fivem-postgres
  postgres:
    image: "postgres" # use latest official postgres version
    container_name: postgres
    env_file:
      - ./Postgres/database.env # configure postgres
    volumes:
      - ./Postgres/postgres-data:/var/lib/postgresql/data
      - ./Postgres/sql-scripts:/docker-entrypoint-initdb.d/
    expose:
      - "5432"
    ports:
      - 5432:5432
    networks:
      - fivem-postgres
networks:
  fivem-postgres:
    driver: bridge
